# GSEA results
## chạy GSEA_GO_ALL
  gsea_all <- gseGO(
    geneList     = gene_list2,
    ont          = "ALL",
    keyType      = "ENSEMBL",
    OrgDb        = org.Hs.eg.db,
    minGSSize    = 3,
    maxGSSize    = 800,
    pvalueCutoff = 0.05,
    verbose      = TRUE
  )
  gse_ALL_sorted <- gsea_all@result[order(gsea_all@result$NES, decreasing = TRUE), ]
  head(gse_ALL_sorted[, c("ID","Description","NES","p.adjust")])
  write.csv(gse_ALL_sorted, 
            file = "/Volumes/Extreme SSD/Thesis/RNAseq_Test/gsea_go_all.csv", 
            row.names = FALSE)




## Vẽ biểu đồ 
###Dotplot cho GO_BP, GO_MF, GO_CC, GO_KEGG
  library(ggplot2)
  library(clusterProfiler)

  p2 <- dotplot(gsea_bp, showCategory = 20, split = ".sign") +  # Load các kết quả GSEA: gsea_bp, gsea_mf, gsea_cc, kk2
    facet_grid(. ~ .sign) +
    scale_size(range = c(2.5, 6)) +   # thu nhỏ kích thước vòng tròn
    theme(
      axis.text.y = element_text(size = 7),   # chữ pathway
      axis.text.x = element_text(size = 7),
      strip.text  = element_text(size = 8),   # chữ tiêu đề facet (UP/DOWN)
      legend.text = element_text(size = 7),
      legend.title= element_text(size = 8),
      plot.title  = element_text(size = 11, hjust = 0.5, face = "plain")
    )

  p2
  #Lưu hình dotplot
  ggsave(
    filename = "/Volumes/Extreme SSD/Thesis/RNAseq_Test/GSEA_GO_BP_dotplot.pdf",
    plot     = p2,
    width    = 8,
    height   = 6
  )

  #Lưu data của dotplot
  p2<-as.data.frame(p2$data)
  write.csv(p2, 
            file = "/Volumes/Extreme SSD/Thesis/RNAseq_Test/dotplot_GO_bp.csv", 
            row.names = FALSE)


###Rigde plot : Grouped by gene set, density plots are generated by using the frequency of fold change values per gene within each set. Helpful to interpret up/down-regulated pathways.

  library(enrichplot)
  library(ggplot2)

  library(dplyr)

  library(dplyr)

  res <- kk2@result  # Load các kết quả GSEAG: gsea_bp, gsea_mf, gsea_cc, kk2

  # 🔴 Top 10 UP (NES lớn nhất)
  top_up <- res %>%
    filter(NES > 0) %>%
    arrange(desc(NES)) %>%   #  NES giảm dần
    head(10)

  # 🔵 Top 10 DOWN (NES âm mạnh nhất)
  top_down <- res %>%
    filter(NES < 0) %>%
    arrange(NES) %>%         # NES tăng dần (âm → nhỏ nhất trước)
    head(10)

  # Gộp lại
  top20 <- bind_rows(top_up, top_down)

  gsea_top20 <- kk2
  gsea_top20@result <- top20

  library(enrichplot)

  p <- ridgeplot(gsea_top20) + labs(x = "enrichment distribution")

  p2 <- p + 
    ggtitle("GSEA – KEGG (Top 10 Up & Down)") +
    theme(
      plot.title  = element_text(size = 10, face = "bold", hjust = 0.5),
      axis.text.y = element_text(size = 6),
      axis.text.x = element_text(size = 8)
    )

  p2

  ggsave(
    "/Volumes/Extreme SSD/Thesis/RNAseq_Test/GSEA_KEGG_ridgeplot_Top10_UpDown.pdf",
    plot = p2, width = 7, height = 5
  )


### Enrichment map: organizes enriched terms into a network with edges connecting overlapping gene sets. In this way, mutually overlapping gene sets are tend to cluster together, making it easy to identify functional modules.


  library(clusterProfiler)
  library(enrichplot)
  # Phân tích kết quả GSEA của: kk2
  kk2 <- pairwise_termsim(kk2) #tính độ giống nhau giữa các pathway 
  p_emap <- emapplot(kk2, showCategory = 20, layout = "kk")

  # chỉnh size chữ pathway (nếu bạn đã làm)
  idx <- which(sapply(p_emap$layers, function(x) inherits(x$geom, "GeomTextRepel")))
  p_emap$layers[[idx]]$aes_params$size <- 3

  # 👉 Thêm tiêu đề
  p_emap <- p_emap +
    ggtitle("GSEA Enrichment Map – KEGG Pathways ") +
    theme(
      plot.title = element_text(size = 12, face = "plain", hjust = 0.5)
    )

  p_emap

  ggsave(
    filename = "/Volumes/Extreme SSD/Thesis/RNAseq_Test/emapplot_gsea_kegg.pdf",
    plot = p_emap,
    width = 8, height = 6, units = "in"
  )

