# Quality Control 

## FastQC
conda install -c bioconda fastqc # cài đặt pagekage 
pwd #/Volumes/Extreme SSD/Thesis/RNAseq_Test/FastQC 
ls #OSCC   Public result

cd OSCC # OSCC chứa file Fastq của 3 mẫu cancer
fastqc -o "/Volumes/Extreme SSD/Thesis/RNAseq_Test/FastQC/result" *.fastq.gz 
cd Public # Public chứa file Fastq của 3 mẫu Normal
fastqc -o "/Volumes/Extreme SSD/Thesis/RNAseq_Test/FastQC/result" *.fastq.gz 

### Kiểm tra kết quả FastQC của mỗi mẫu -> Thực hiện Trim adapter cho toàn bộ mẫu, không xoá Duplicate

## Trim Galore
conda activate base #kích hoạt môi trường
conda install -c bioconda trim-galore # cài Trim Galore
trim_galore –version #Trimgalore version: 0.6.10
cutadapt --version #Cutadapt version: 5.1

cd OSCC # OSCC chứa file Fastq của 3 mẫu cancer
# Mẫu cancer 167
    trim_galore \  
    --paired \ 
    --illumina \  # Loại adapter của illumina
    --quality 20 \  # cắt base có Q < 20 từ đầu 3’ end. Iluumina đầu 3’ thường xấu . Cắt quality trước rồi mới đến adapter trimming
    --length 30 \ # bỏ read < 30 bp
    --clip_R1 12 \  #cắt 12 bp đầu 5’ (giảm bias RNA-seq)
    --clip_R2 12 \  
    --cores 4 \  
    RNA-167_S4_L001_R1_001.fastq.gz \  RNA-167_S4_L001_R2_001.fastq.gz

# Mẫu cancer 170
trim_galore \  --paired \  --illumina \  --quality 20 \  --length 30 \  --clip_R1 12 \  --clip_R2 12 \  --cores 4 \  RNA-170_S4_L001_R1_001.fastq.gz \  RNA-170_S4_L001_R2_001.fastq.gz
# Mẫu cancer 260
trim_galore \  --paired \  --illumina \  --quality 20 \  --length 30 \  --clip_R1 12 \  --clip_R2 12 \  --cores 4 \  RNA-260_S2_L001_R1_001.fastq.gz \  RNA-260_S2_L001_R2_001.fastq.gz

cd Public # Public chứa file Fastq của 3 mẫu Normal
# Mẫu normal SRR3820341
trim_galore \  --paired \  --illumina \  --quality 20 \  --length 30 \  --clip_R1 12 \  --clip_R2 12 \  --cores 4 \  SRR3820341_1.fastq.gz \  SRR3820341_2.fastq.gz
# Mẫu normal SRR3820365
trim_galore \  --paired \  --illumina \  --quality 20 \  --length 30 \  --clip_R1 12 \  --clip_R2 12 \  --cores 4 \  SRR3820365_1.fastq.gz \  SRR3820365_2.fastq.gz
# Mẫu normal SRR3820450
trim_galore \  --paired \  --illumina \  --quality 20 \  --length 30 \  --clip_R1 12 \  --clip_R2 12 \  --cores 4 \  SRR3820450_1.fastq.gz \  SRR3820450_2.fastq.gz

### Thực hiện lại FastQC sau khi trimming
cd OSCC
cd Triming # chứa file fastq đã trimming của 3 mẫu cancer
fastqc -o “/Volumes/Extreme SSD/Thesis/RNAseq_Test/FastQC/result/OSCC” *.fq.gz
cd Public
cd Triming # chứa file fastq đã trimming của 3 mẫu normal
fastqc -o “/Volumes/Extreme SSD/Thesis/RNAseq_Test/FastQC/result/Public” *.fq.gz

### Kiểm tra kết quả FastQC sau trimming của mỗi mẫu -> INPUT của Kallisto
